apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flask-app
  name: flask-app
  namespace: exam-36
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  strategy: {}
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - image: devvinc/flask-app:v2
          name: flask-app
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          env:
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: info
                  key: env
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: info
                  key: log_level
            - name: GRPC_PORT
              valueFrom:
                configMapKeyRef:
                  name: info
                  key: grpc_port
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: secret-database
                  key: DB_URI
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CPU 
              valueFrom:
                 resourceFieldRef:
                   containerName: flask-app
                   resource: requests.cpu
            - name: MEMORY
              valueFrom:
                 resourceFieldRef:
                   containerName: flask-app
                   resource: requests.memory
