---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    author: negmatov
    project: practice
  name: nginx1
  namespace: exam-36
spec:
  containers:
  - image: nginx
    name: nginx1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    author: negmatov
    project: practice
  name: nginx2
  namespace: exam-36
spec:
  containers:
  - image: nginx
    name: nginx2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
